name: Convert V2RayLink to Clash

on:

  workflow_dispatch:

  schedule:

    - cron: '0 0 * * *' # Run the workflow daily at midnight

jobs:

  convert:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository

        uses: actions/checkout@v2

      - name: Install clashctl

        run: |

          sudo curl -L https://github.com/Dreamacro/clash/releases/latest/download/clash-linux-amd64.gz -o /usr/local/bin/clash.gz

          sudo gunzip -f /usr/local/bin/clash.gz

          sudo chmod +x /usr/local/bin/clash

      - name: Get V2RayLink

        run: |

          curl -sSL 'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt' > raw.txt

      - name: Convert to Clash

        run: |

          clash -i raw.txt -o /subscribe/raw.txt

