
name: Convert V2Ray Link to Clash

on:

  workflow_dispatch:

  schedule:

    - cron: '0 0 * * *' # Run everyday at midnight

env:

  CONVERTER_VERSION: 'v1.0.0'

  SUBSCRIBE_DIR: 'subscribe'

  RAW_FILE: 'raw.txt'

jobs:

  convert:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository

        uses: actions/checkout@v3

      - name: Install Python

        uses: actions/setup-python@v2

        with:

          python-version: '3.x'

      - name: Install Dependencies

        run: pip install v2ray-config==1.1.0

      - name: Get V2Ray Link

        run: curl -sSL 'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt' > v2ray_links.txt

      - name: Convert V2Ray Link to Clash- name: Convert V2Ray Link to Clash
        run: |
          python -c "from v2ray_config import V2rayConfig; V2rayConfig('v2ray_links.txt').to_clash('raw.txt')"

      - name: Prepare Subscribe Directory
        run: mkdir -p ${{ env.SUBSCRIBE_DIR }}

      - name: Move Raw File to Subscribe Directory
        run: mv ${{ env.RAW_FILE }} ${{ env.SUBSCRIBE_DIR }}/${{ env.RAW_FILE }}

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.SUBSCRIBE_DIR }}/${{ env.RAW_FILE }}
          git commit -m "Update raw.txt"
          git push
