name: "Proxies Subs"
on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * *'
env:
  RESULT: 'proxies-subs.yml'
jobs:
  running:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64.tar.gz
          sudo tar xvf yq_linux_amd64.tar.gz
          sudo mv yq_linux_amd64 yq
          sudo chmod +x yq
          sudo mv yq /usr/local/bin/
      - name: Get Proxies
        run: |
          curl -sSL 'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml' > ./raw.yaml
      - name: proccess
        run: |
          # filter ((vmess|trojan) & (websocket))


          yq '[.proxies.[] | select((.type == "vmess" or .type == "trojan") and (.alterId == 0) and (.port == 443) and (.tls == true) and (.network == "ws")) | .server = "104.16.66.85"]' ./raw.yaml \
          | yq '{"proxies": .}' > ${{ env.RESULT }}
      - name: Prepare
        run: |
          echo "RELEASE_NAME=Updated on $(date +%F)" >> $GITHUB_ENV
          mkdir -p subscribe
          cp ${{ env.RESULT }} ./subscribe/
      - name: Push to "subscribe" dir
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./subscribe/.
          git commit -m "${{ env.RELEASE_NAME }}"
          git push
