name: speedtest

# 触发条件

on:

  workflow_dispatch:

  

  schedule:

    - cron: '30 */8 * * *'

  

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2


    - name: Set Timezone

      run: sudo timedatectl set-timezone 'Asia/Jakarta'

    - name: Run Lite Speedtest

      run: |

        chmod +x ./lite-linux-amd64
        ./lite-linux-amd64 --config ./config.json --test https://raw.githubusercontent.com/ardi5209/akun/main/sing-box-base64.txt

        
    - name: Commit changes

      run: |                 

        git config --local user.email "actions@github.com"

        git config --local user.name "GitHub Actions"

        git add .

        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') Filter Nodes"
        git push
