
name: Run PHP Script

on:

  workflow_dispatch:

  schedule:

    - cron: '0 */2 * * *' # Menjadwalkan menjalankan workflow setiap hari jam 00:00 UTC

jobs:

  run-php-script:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
      - name: Set up PHP

        uses: shivammathur/setup-php@v2

        with:

          php-version: '8.0' # Versi PHP yang digunakan
      - name: Install Composer dependencies
        run: composer install
      - name: Run PHP Script
        run: |
           php script.php
           yq e '[.proxies.[] | select((.port == 443) and(.alterId == 0) and (.servername != "") and (.tls== true) and (.network == "ws")) | .server = "104.16.66.85"]' a.yaml | yq e '{"proxies": .}' > b.yaml
           php convert.php
      - name: Set up Node.js

        uses: actions/setup-node@v2

        with:

          node-version: '14'

      - name: Install Dependencies

        run: npm install

      - name: Read File Content

        id: read-file
  
        run: echo "::set-output name=content::$(cat sing-box.txt)"

      - name: Encode using Base64

        id: encode-base64

        run: echo "${{ steps.read-file.outputs.content }}" | base64 --wrap=0 > sing-box-base64.txt
      - name: Commit and Push Changes

        run: |

          git config --local user.name "github-actions[bot]"

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git commit -m "Update data"

          git push
