name: Run PHP Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # Schedule the workflow to run every two hours

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.8' # Specify the PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHP Script
        run: php script.php
        
      - name: Commit Changesss
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add .
          git checkout main
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main

      - name: Process YAML files
        run: |
          yq e '[.proxies.[] | select((.network == "ws") and (.tls == true))]' a.yaml | yq e '{"proxies": .}' > b.yaml
      - name: Commit Changess
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add .
          git checkout main
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          
      - name: Convert And Speedtest
        run : php convert.php
      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add .
          git checkout main
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
      
      - name: Speedtest
        run: php speedtest.php
        
      - name: Pull Changes
        run: git pull origin main
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update data"
          git push
