
name: Run PHP Script

on:

  workflow_dispatch:

  schedule:

    - cron: '0 0 * * *' # Menjadwalkan menjalankan workflow setiap hari jam 00:00 UTC

jobs:

  run-php-script:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
      - name: Set up PHP

        uses: shivammathur/setup-php@v2

        with:

          php-version: '7.4' # Versi PHP yang digunakan

      - name: Run PHP Script

        run: |
           php script.php
           yq e '[.proxies.[] | select((.port == 443) and(.alterId == 0) and ((.servername != "") or (.servername != "ws-aicdn.com")) and (.tls == true) and (.network == "ws")) | .server = "104.16.66.85"]' a.yaml | yq e '{"proxies": .}' > b.yaml

      - name: Commit and Push Changes

        run: |

          git config --local user.name "github-actions[bot]"

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git commit -m "Update data"

          git push
