name: Test VPN Connections Golang

on:
  workflow_dispatch:

jobs:
  test-connections:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and Run Golang Script
      run: |
        go mod init tes_koneksi.go
        go get github.com/gorilla/websocket
        go get gopkg.in/yaml.v2
        go mod tidy
        go mod vendor
        go build -o test-connections tes_koneksi.go
        ./test-connections

    - name: Clean Up
      run: |
        rm -f test-connections