name: Test VPN Connections Golang

on:
  workflow_dispatch:

jobs:
  test-connections:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and Run Golang Script
      run: |
        go build -o test-connections main.go
        ./test-connections

    - name: Clean Up
      run: |
        rm -f test-connections